name: DXL core module pull request workflow

on:
    push:
        branches:
            - staging

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Create Pull request agains master branch
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: ${{ github.event.head_commit.message }}
                title: ${{ github.event.head_commit.message }}
                body: 'This is an automated pull request from staging to master'
                branch: staging
                base: master
                branch-suffix: staging
                labels: staging
                assignees: ${{ github.actor }}
                reviewers: ${{ github.actor }}
              